### ISSUE TITLE
Move active window to screen

### ISSUE THREAD

**Issue by leukipp** [leukipp/cortile#67]
Starting with [v2.5.2](https://github.com/leukipp/cortile/releases/tag/v2.5.2) additional keyboard shortcuts are available to move the current active (focused) window to the next or previous screen:
```toml
# Move the active window to the next screen (KP_9 = Num_9).
screen_next = "Control-Shift-KP_9"

# Move the active window to the previous screen (KP_7 = Num_7).
screen_previous = "Control-Shift-KP_7"
```
