### ISSUE TITLE
Move active window using a hotkey

### ISSUE THREAD

**Issue by navewindre** [leukipp/cortile#80]
i've read through past issues and saw that support for window move events from external processes is not planned, however it would be nice to be able to move slave and even master windows up/down the stack in the layout using a hotkey. apologize if i'm wrong but i've read through the config options diligently and didn't spot that as a feature. i've tried achieving it using openbox's MoveResizeTo and an xdotool windowmove/windowsize script but neither were successful, as cortile simply snaps the windows back to their original position.

also thanks for creating this wonderful software, it's been a joy to use in general.

**Comment by leukipp** [comment]
> however it would be nice to be able to move slave and even master windows up/down the stack in the layout using a hotkey

If by "up/down moving" you are referring to bringing the window to the front or sending it to the back of the stack (the z coordinate), you can simply change the window focus. This can be done using the cortile hotkeys or through the built-in features of your operating system.

But I think you where referring to moving the window position along the x/y coordinates, which would result in swapping windows, like it happens per drag & drop per mouse.

> i've tried achieving it using openbox's MoveResizeTo and an xdotool windowmove/windowsize script but neither were successful, as cortile simply snaps the windows back to their original position.

There is already a way to programmatically move windows along the x/y coordinates via [dbus](https://github.com/leukipp/cortile/issues/51), such that a swap event is triggered. e.g.:
```bash
cortile dbus -method WindowToPosition int:id int:x int:y
```

Keep in mind that the x/y coordinate logic will only work if your physical workplace configuration (screens/resolution/etc.) will always stay the same. If you need some more sophisticated logic (e.g.: always move a special window to the lower right corner) you may want to have a look into the [python extensions](https://github.com/leukipp/cortile/issues/65).

Once the next release is published, dedicated keyboard shortcuts will be available to swap the active window with the next/previous window.

**Comment by leukipp** [comment]
Starting with [v2.5.3](https://github.com/leukipp/cortile/releases/tag/v2.5.3) additional keyboard shortcuts are available to swap the current active (focused) window with the next or previous window:
```toml
# Move the active window to the next position (KP_3 = Num_3).
position_next = "Control-Shift-KP_3"

# Move the active window to the previous position (KP_1 = Num_1).
position_previous = "Control-Shift-KP_1"
```

If you want to use this feature, you will have to manually add it into your existing [config.toml](https://github.com/leukipp/cortile/blob/main/config.toml) file. Nothing will change for you, if you don't want to add this feature.

In case you want to use this, keep in mind that those keyboard shortcuts where already in use in previous cortile releases. For consistency the [default keyboard config](https://github.com/leukipp/cortile/blob/main/config.toml#L123) has been updated:
```toml
# Increase the proportion of master-slave area (Insert = Ins).
#proportion_increase = "Control-Shift-KP_3"
proportion_increase = "Control-Shift-Insert"

# Decrease the proportion of master-slave area (Delete = Del).
#proportion_decrease = "Control-Shift-KP_1"
proportion_decrease = "Control-Shift-Delete"
```
